<!DOCTYPE html>
<html lang="ja-JP">
<head>
	<meta charset="utf-8">
	<meta name="author" content="reinforchu">
	<meta name="description" content="twitter しりとり">
	<meta name="keywords" content="Shiritori,しりとり,twitter,リインフォース,reinforchu">
	<meta name="robots" content="index,follow,noarchive">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="vnd.up.bookmark" p:forua="true" content="http://xn--eckk2c4f8d7b7c.jp/"><!-- XHTML has a mix that HTML5 is a known issue. -->
	<title>twitter しりとり</title>
	<link rel="shortcut icon" href="http://xn--eckk2c4f8d7b7c.jp/schwertkreuz.ico" type="image/vnd.microsoft.icon">
	<link rel="stylesheet" href="http://file.reinforce.tv/bootstrap/v2.1.1/css/bootstrap.min.css" type="text/css">
	<script src="http://code.jquery.com/jquery-1.7.2.min.js"></script>
	<script src="http://file.reinforce.tv/bootstrap/v2.1.1/assets/js/bootstrap-transition.js"></script>
	<script src="http://file.reinforce.tv/bootstrap/v2.1.1/assets/js/bootstrap-collapse.js"></script>
	<script src="http://file.reinforce.tv/bootstrap/v2.1.1/js/bootstrap.min.js"></script>
	<style type="text/css">
		body {
			color: #072766;
			background-color: #ffffff;
			background: transparent url('http://xn--eckk2c4f8d7b7c.jp/files/webx-bkg.png') repeat-x;
			padding-top: 60px;
			padding-bottom: 40px;
			margin-left: 0px;
			margin-right: 0px;
			line-height: 115%;
			font-family: 'Meiryo UI','メイリオ','ヒラギノ角ゴ Pro W3','Hiragino Kaku Gothic Pro',Tahoma;
		}
		a:link { color: #0084B4; }
		a:visited { color: #0084b4; }
		a:active { color: #269abd; }
		a:hover { color: #16d6e0; }
		img {border: none;}
		form { display: inline; }
		#TextShadow { text-shadow: 5px 5px 15px black; }
		#BoxShadow { box-shadow: 3px 3px 5px black; }
		#MainBoxShadow { box-shadow: 2px 2px 3px black; }
		#BarAlpha {
			Filter: Alpha(Opacity=95);
			opacity: .95;
		}
		#Alpha {
			Filter: Alpha(Opacity=75);
			opacity: .75;
		}
		#WhiteColor {
			Color: #FFFFFF;
		}
	</style>
	<link rel="stylesheet" href="http://file.reinforce.tv/bootstrap/v2.1.1/css/bootstrap-responsive.min.css" type="text/css">
</head>
<body>
