<!-- body -->
<!-- Fixed NavigationBar -->
<div class="navbar navbar-inverse navbar-fixed-top" id="BoxShadow">
	<div class="navbar-inner" style="text-align: center;">
		<div class="container">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>
			<a class="brand" href="http://xn--eckk2c4f8d7b7c.jp/" title="リインフォース.jp" target="_blank">Shiritori</a>
			<div class="nav-collapse">
				<ul class="nav">
					<li><a href="./" title="Home" target="_self"><i class="icon-home icon-white"></i>Home</a></li>
				</ul>
				<p class="navbar-text pull-right">
					<b><a href="./?reset" title="ゲームをリセット" target="_self" class="btn"><i class="icon-remove"></i>リセット</a></b>
				</p>
			</div><!-- nav-collapse -->
		</div><!-- container -->
	</div><!-- navbar-inner -->
</div><!-- navbar navbar-fixed-top -->
<!-- End of Fixed NavigationBar -->
