<!-- Footer -->
<div class="container" style="text-align: center;">
	<div class="span11">
		<hr>
		<footer>
			<!-- twitter Share button -->
			<a href="https://twitter.com/share" class="twitter-share-button" data-url="http://xn--eckk2c4f8d7b7c.jp/shiritori/" data-text="twitter しりとり - リインフォース.jp" data-lang="en" data-size="large" data-hashtags="twSiri">Share!</a>
			<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
			<!-- End of twitter Share button -->
			<br>
			<!-- twitter Follow button - en (modified) -->
			<a href="https://twitter.com/reinforchu" class="twitter-follow-button" data-size="large" data-lang="en">@reinforchu Follow us on twitter!</a>
			<script src="//platform.twitter.com/widgets.js" type="text/javascript"></script>
			<!-- End of twitter Follow button - en (modified) -->
		</footer>
	</div><!-- span11 -->
</div><!-- container -->
<!-- End of Footer -->
<p><br><br></p>
<!-- End of body -->
</body>
</html>